<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * P5-A0 — partitioned, append-only analytics event foundation (D-037).
 *
 * No transactional foreign key is allowed here. The restricted application
 * runtime receives no access in this gate; a future ingestion authority must be
 * designed and granted separately.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                public_id UUID NOT NULL,
                occurred_at TIMESTAMPTZ NOT NULL,
                visitor_id UUID,
                user_id BIGINT,
                session_id UUID,
                event_name VARCHAR(64) NOT NULL,
                entity_type VARCHAR(32),
                entity_id BIGINT,
                properties JSONB NOT NULL,
                page_path VARCHAR(2048),
                referrer_host VARCHAR(253),
                utm_source VARCHAR(255),
                utm_medium VARCHAR(255),
                utm_campaign VARCHAR(255),
                device_type VARCHAR(16),
                country_code VARCHAR(2),
                ip_hash VARCHAR(64),
                ip_hash_key_version SMALLINT,
                created_at TIMESTAMPTZ NOT NULL,

                CONSTRAINT events_pkey PRIMARY KEY (id, occurred_at),
                CONSTRAINT events_event_name_format_check
                    CHECK (event_name ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'),
                CONSTRAINT events_entity_reference_consistency_check
                    CHECK (
                        CASE
                            WHEN entity_type IS NULL AND entity_id IS NULL THEN TRUE
                            WHEN entity_type IS NOT NULL
                                AND entity_type ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'
                                AND entity_id IS NOT NULL
                                AND entity_id > 0
                            THEN TRUE
                            ELSE FALSE
                        END IS TRUE
                    ),
                CONSTRAINT events_properties_object_check
                    CHECK (jsonb_typeof(properties) = 'object'),
                CONSTRAINT events_properties_size_check
                    CHECK (octet_length(properties::text) <= 16384),
                CONSTRAINT events_page_path_format_check
                    CHECK (
                        page_path IS NULL OR (
                            left(page_path, 1) = '/'
                            AND left(page_path, 2) <> '//'
                            AND strpos(page_path, '://') = 0
                            AND strpos(page_path, '?') = 0
                            AND strpos(page_path, '#') = 0
                            AND strpos(page_path, E'\r') = 0
                            AND strpos(page_path, E'\n') = 0
                        )
                    ),
                CONSTRAINT events_referrer_host_format_check
                    CHECK (
                        referrer_host IS NULL OR (
                            referrer_host = btrim(referrer_host)
                            AND referrer_host = lower(referrer_host)
                            AND referrer_host ~ '^[a-z0-9]([a-z0-9.-]{0,251}[a-z0-9])?$'
                            AND referrer_host !~ '\.\.'
                        )
                    ),
                CONSTRAINT events_utm_source_format_check
                    CHECK (utm_source IS NULL OR utm_source ~ '^[a-z0-9][a-z0-9._-]*$'),
                CONSTRAINT events_utm_medium_format_check
                    CHECK (utm_medium IS NULL OR utm_medium ~ '^[a-z0-9][a-z0-9._-]*$'),
                CONSTRAINT events_utm_campaign_format_check
                    CHECK (utm_campaign IS NULL OR utm_campaign ~ '^[a-z0-9][a-z0-9._-]*$'),
                CONSTRAINT events_device_type_check
                    CHECK (device_type IS NULL OR device_type IN ('desktop', 'mobile', 'tablet', 'bot', 'other')),
                CONSTRAINT events_country_code_format_check
                    CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$'),
                CONSTRAINT events_ip_hash_consistency_check
                    CHECK (
                        CASE
                            WHEN ip_hash IS NULL AND ip_hash_key_version IS NULL THEN TRUE
                            WHEN ip_hash IS NOT NULL
                                AND ip_hash ~ '^[0-9a-f]{64}$'
                                AND ip_hash_key_version IS NOT NULL
                                AND ip_hash_key_version > 0
                            THEN TRUE
                            ELSE FALSE
                        END IS TRUE
                    ),
                CONSTRAINT events_created_after_occurrence_check
                    CHECK (created_at >= occurred_at)
            ) PARTITION BY RANGE (occurred_at);

            CREATE TABLE events_default PARTITION OF events DEFAULT;

            CREATE UNIQUE INDEX events_public_id_occurred_at_unique
                ON events (public_id, occurred_at);
            CREATE INDEX events_event_name_occurred_at_index
                ON events (event_name, occurred_at DESC);
            CREATE INDEX events_visitor_id_occurred_at_index
                ON events (visitor_id, occurred_at DESC)
                WHERE visitor_id IS NOT NULL;
            CREATE INDEX events_session_id_occurred_at_index
                ON events (session_id, occurred_at DESC)
                WHERE session_id IS NOT NULL;
            CREATE INDEX events_entity_occurred_at_index
                ON events (entity_type, entity_id, occurred_at DESC)
                WHERE entity_type IS NOT NULL;
            CREATE INDEX events_utm_campaign_occurred_at_index
                ON events (utm_campaign, occurred_at DESC)
                WHERE utm_campaign IS NOT NULL;
            SQL);

        DB::unprepared(<<<'SQL'
            CREATE OR REPLACE FUNCTION prevent_analytics_events_mutation()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'analytics events are append-only';
            END;
            $$;

            CREATE TRIGGER analytics_events_prevent_mutation_trigger
            BEFORE UPDATE OR DELETE ON events
            FOR EACH ROW
            EXECUTE FUNCTION prevent_analytics_events_mutation();
            SQL);

        // P4-B0 grants future tables/sequences to the general runtime by
        // default. Analytics stays dark in P5-A0, so revoke every inherited
        // capability explicitly on the parent, its partition and its identity.
        DB::statement('REVOKE ALL PRIVILEGES ON TABLE events, events_default FROM PUBLIC, digitrove_runtime');
        DB::statement('REVOKE ALL PRIVILEGES ON SEQUENCE events_id_seq FROM PUBLIC, digitrove_runtime');
        DB::statement('REVOKE ALL PRIVILEGES ON FUNCTION prevent_analytics_events_mutation() FROM PUBLIC, digitrove_runtime');
    }

    public function down(): void
    {
        DB::statement('DROP TRIGGER IF EXISTS analytics_events_prevent_mutation_trigger ON events');
        DB::statement('DROP FUNCTION IF EXISTS prevent_analytics_events_mutation()');
        DB::statement('DROP TABLE IF EXISTS events CASCADE');
    }
};
